try guile156 too

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20547,6 +20547,51 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
   fi
+  if test x"$sim_ac_have_libscenery" = x"false"; then
+    # maybe with our special Guile156
+    sim_ac_libscenery_libs="${sim_ac_libscenery_libs}156"
+    LIBS="$sim_ac_libscenery_libs $sim_ac_libscenery_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <sim/scenery/scenery.h>
+
+int
+main ()
+{
+
+      ss_initialize();
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+      sim_ac_have_libscenery=true
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  fi
 
   CPPFLAGS=$sim_ac_libscenery_save_CPPFLAGS
   LDFLAGS=$sim_ac_libscenery_save_LDFLAGS
